### ISSUE TITLE
URL Regex not matching some valid URLs

### ISSUE THREAD

**Issue by Fidget-Spinner** [ninoseki/ioc-extractor#141]
Hello, I really like this library, however recently I've come across a problem.

I noticed that when extracting IOC, 
```
Input: (Valid URL)
https://1.1.1.1.domain.com:443

Expected output:
https://1.1.1.1.domain.com:443

Actual output:
https://1.1.1.1

```
I looked around and I believe that the url regex is causing the issue, specifically: 
```javascript
const url = `(?:${protocol})${auth}(?:localhost|${ipv4}|${domain})${port}${path}`;
```
Once localhost or ipv4 match is found, the group drops the rest.
This means this also produces unexpected output:
```
Input: (Valid URL)
https://localhost.domain.com:443

Expected output:
https://localhost.domain.com:443

Actual output:
https://localhost

```
Edit: Just to test my theory:
```
Input: (Valid URL)
https://1.1.1.domain.com:443

Expected output:
https://1.1.1.domain.com:443

Actual output: (this is correct)
https://1.1.1.domain.com:443

```
This shows that once ipv4 does not match, domain match is used instead.

Thank you for your time!

Edit 2:
I found a simple fix for the bug:
```javascript
const url = `(?:${protocol})${auth}(?:${domain}|localhost|${ipv4})${port}${path}`;
```

**Comment by ninoseki** [comment]
Thanks, the issue will be fixed in the next release.
