### ISSUE TITLE
Email Regex does not include dashes

### ISSUE THREAD

**Issue by thehappydinoa** [ninoseki/ioc-extractor#203]
For both `emailRegex` and `nonStrictEmailRegex` they do not account for dashes in the email addresses. By adding a dash like: `[A-Za-z0-9_.-]` it should capture more addresses.

https://github.com/ninoseki/ioc-extractor/blob/5815c6d94b2092369632b9923a538033b21164c6/src/aux/regexes.ts#L142-L144

**Comment by ninoseki** [comment]
Thank you for pointing out the issue.
