### ISSUE TITLE
URLs that do not start with https?://

### ISSUE THREAD

**Issue by panzukai** [ninoseki/ioc-extractor#316]
I have noticed in my usage that researchers may simply report a url in the form:  `domain[.]tld/someURI`

The extractIOC function is not returning these in the iocs.urls array.  Just getting domain in the domains array.

Could add another option for strictURLs maybe that makes the https?:// part of the regex optional if the option is set to false.  Or simply make it optional without an option setting.

**Comment by ninoseki** [comment]
Literally it's not a URL and the protocol is missing.
So it's impossible to infer it.
