### ISSUE TITLE
Domain extractor regex suffers from catastrophic backtracking

### ISSUE THREAD

**Issue by yssrku** [ninoseki/ioc-extractor#334]
Hi 

I found the domain regex used in this package will take a unexpected long time to process inputs that contains strings like this
```
somelongishstring.somelongishstring.somelongishstring.somelongishstring.somelongishstring.somelongishstring
```

As this is likely due to catastrophic backtracking, I was able to mitigate this by adding positive look-ahead to the beginning of domain regex,
something like `(?=[${labelLetters}.\\-]{1,252}\\.(${tld})\\b)`

I'm not sure if this fix is adequate though.

**Comment by ninoseki** [comment]
Thanks for the heads up!
